// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// package local handles command line parameters and execution logic for local run
package local

import (
	"net/url"
	"os"
	"os/exec"
	"path"
	"strconv"

	"github.com/spf13/cobra"
	"google.golang.org/adk/cmd/adkgo/root/run"
	"google.golang.org/adk/internal/cli/util"
)

type localServerFlags struct {
	port int    // command line param
	url  string // autogenerated
}

type buildFlags struct {
	skipCleaning bool   // command line param
	tempDir      string // command line param
	uiBuildDir   string // autogenerated
	execPath     string // autogenerated
}

type sourceFlags struct {
	uiDir          string // command line param
	srcBasePath    string // command line param
	entryPointPath string // command line param
}

type webUIDeployFlags struct {
	backendUri string // autogenerated
}

type runLocalFlags struct {
	server localServerFlags
	build  buildFlags
	source sourceFlags
	webUI  webUIDeployFlags
}

var flags runLocalFlags

// localCmd represents the cloudrun command
var localCmd = &cobra.Command{
	Use:   "local",
	Short: "Runs a local server with WebUI.",
	Long: `
	Starts a local server on the given port. ADK Web UI runs on '/ui/' and ADK REST API runs on '/api/'
	You need: 
	  - a downloaded version of adk-web (available at https://github.com/google/adk-web)
	  - an ability to build adk-web (prerequisites on  https://github.com/google/adk-web):
	  	npm  (node js: see https://nodejs.org/en/download)
		ng (anglural cli: see https://angular.dev/tools/cli/setup-local)		
	  - go

	Building the adk-web takes a while, so it is built once unless you force cleaning by providing --skipCleaning=false
	After you change the serverPort you will also need to force cleaning and build adk-web anew (due to change of the backend endpoint)
	`,
	RunE: func(cmd *cobra.Command, args []string) error {
		err := flags.runLocal()
		return err
	},
}

func init() {
	run.RunCmd.AddCommand(localCmd)

	localCmd.PersistentFlags().StringVarP(&flags.build.tempDir, "tempDir", "t", "", "Temp dir for build")
	localCmd.PersistentFlags().BoolVarP(&flags.build.skipCleaning, "skipCleaning", "c", true, "Set to true in order to clean build")
	localCmd.PersistentFlags().IntVarP(&flags.server.port, "serverPort", "s", 8080, "Local proxy port")
	localCmd.PersistentFlags().StringVarP(&flags.source.uiDir, "webUIDir", "u", "", "ADK Web UI base dir")
	localCmd.PersistentFlags().StringVarP(&flags.source.entryPointPath, "entryPoint", "e", "", "Path to an entry point (go 'main'). ")
	localCmd.PersistentFlags().StringVarP(&flags.source.srcBasePath, "srcPath", "p", "", "Path to an base path of your project")
}

func (f *runLocalFlags) computeFlags() error {
	err := util.LogStartStop("Computing flags",
		func(p util.Printer) error {
			f.build.uiBuildDir = path.Join(f.build.tempDir, "ui")
			f.build.execPath = path.Join(f.build.tempDir, "server")
			f.server.url = "http://localhost:" + strconv.Itoa(f.server.port)
			url, err := url.JoinPath(f.server.url, "api")
			f.webUI.backendUri = url
			return err
		})
	return err
}

func (f *runLocalFlags) cleanTemp() error {
	err := util.LogStartStop("Cleaning temp",
		func(p util.Printer) error {
			if f.build.skipCleaning {
				p("Cleaning skipped", f.build.tempDir)
				return nil
			}
			p("Clean temp starting with", f.build.tempDir)
			err := os.RemoveAll(f.build.tempDir)
			if err != nil {
				return err
			}
			return os.MkdirAll(f.build.tempDir, os.ModeDir|0700)
		})
	return err
}

func (f *runLocalFlags) makeDirs() error {
	err := util.LogStartStop("Make build dirs",
		func(p util.Printer) error {
			p("Making", f.build.uiBuildDir)
			return os.MkdirAll(f.build.uiBuildDir, os.ModeDir|0700)
		})
	return err
}

func (f *runLocalFlags) setBackendForAdkWebUI() error {

	err := util.LogStartStop("Setting backend for Adk Web UI",
		func(p util.Printer) error {
			cmd := exec.Command("npm", "run", "inject-backend", "--backend="+f.webUI.backendUri)
			cmd.Dir = f.source.uiDir
			return util.LogCommand(cmd, p)
		})
	return err
}

func (f *runLocalFlags) makeDistForAdkWebUI() error {
	err := util.LogStartStop("Making dist for Adk Web UI",
		func(p util.Printer) error {

			fileToCheck := path.Join(f.build.uiBuildDir, "browser/index.html")
			_, err := os.Stat(fileToCheck)
			if err == nil {
				p("File", fileToCheck, "found, building skipped")
				return nil
			}
			// else
			p("File", fileToCheck, "not found, building from scratch")
			cmd := exec.Command("ng", "build", "--output-path="+f.build.uiBuildDir)
			cmd.Dir = f.source.uiDir
			return util.LogCommand(cmd, p)
		})
	return err
}

func (f *runLocalFlags) compileEntryPoint() error {
	err := util.LogStartStop("Compiling server",
		func(p util.Printer) error {
			p("Using", f.source.entryPointPath, "as entry point")
			cmd := exec.Command("go", "build", "-o", f.build.execPath, f.source.entryPointPath)

			cmd.Dir = f.source.srcBasePath
			cmd.Env = append(os.Environ(), "CGO_ENABLED=0", "GOOS=linux")
			return util.LogCommand(cmd, p)
		})
	return err
}

func (f *runLocalFlags) runLocalServer() error {
	err := util.LogStartStop("Running local server",
		func(p util.Printer) error {
			cmd := exec.Command(f.build.execPath,
				"--port", strconv.Itoa(f.server.port),
				"--front_address", "localhost:"+strconv.Itoa(f.server.port),
				"--start_restapi=true",
				"--start_webui=true",
				"--webui_path", "./ui/browser/",
			)

			cmd.Dir = f.build.tempDir

			p("--------------------------------------------------------------------------")
			p("         Running ADK Web UI on http://localhost:" + strconv.Itoa(f.server.port) + "/ui/    <-- open this ")
			p("               ADK REST API on http://localhost:" + strconv.Itoa(f.server.port) + "/api/                 ")
			p("                                                                          ")
			p("                          Press Ctrl-C to stop                            ")
			p("--------------------------------------------------------------------------")
			return util.LogCommand(cmd, p)
		})
	return err
}

func (f *runLocalFlags) runLocal() error {
	var err error

	err = f.computeFlags()
	if err != nil {
		return err
	}
	err = f.cleanTemp()
	if err != nil {
		return err
	}
	err = f.makeDirs()
	if err != nil {
		return err
	}
	err = f.setBackendForAdkWebUI()
	if err != nil {
		return err
	}
	err = f.makeDistForAdkWebUI()
	if err != nil {
		return err
	}
	err = f.compileEntryPoint()
	if err != nil {
		return err
	}
	err = f.runLocalServer()
	if err != nil {
		return err
	}

	return nil
}
